---
  version: 0.2
  
  phases:
    build:
      commands:
        - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
        - curl -O https://bootstrap.pypa.io/get-pip.py
        - python get-pip.py
        - pip install awscli
        - aws --version
        - curl -qL -o aws_credentials.json http://169.254.170.2/$AWS_CONTAINER_CREDENTIALS_RELATIVE_URI > aws_credentials.json
        - aws configure set region $AWS_REGION
        - aws configure set aws_access_key_id `./jq -r '.AccessKeyId' aws_credentials.json`
        - aws configure set aws_secret_access_key `./jq -r '.SecretAccessKey' aws_credentials.json`
        - aws configure set aws_session_token `./jq -r '.Token' aws_credentials.json`
        - ls -al
        - yum install -y zip git
        - cd web\ files && sed -i 's@#00a1db@'"$SITEPRIMARY"'@' scss/_theme-variables.scss
        - cd web\ files && sed -i 's@#d30b5c@'"$SITESECONDARY"'@' scss/_theme-variables.scss
        - cd web\ files && sed -i 's@#ff9b01@'"$SITETERTIARY"'@' scss/_theme-variables.scss
        - cd web\ files && sed -i 's@spacejet-logo.png@'"$LOGONAME"'@' templates/navigation/top-nav.tpl
        - cd web\ files && sed -i 's@spacejet-logo.png@'"$LOGONAME"'@' templates/navigation/mobile-menu.tpl
        - cd web\ files && sed -i 's@spacejet-logo.png@'"$LOGONAME"'@' templates/footer/footer.tpl
        - zip --symlinks -r spacejet.zip web\ files www config.json
        - mkdir marketplace
        - cd marketplace
        - git init
        - git remote add origin https://${GITUSER}:${GITTOKEN}@github.com/${GITORG}/${GITREPO}.git
        - git config --global user.email "${GITUSER}@solodev.com"
        - git config --global push.default simple
        - git pull origin master
        - mv ../spacejet.zip depot/themes/
        - cd depot/themes
        - git add spacejet.zip
        - git commit -m "Updating SpaceJet Theme"
        - git push origin master
        - rm -Rf spacejet.zip
